package ch5.exceptions;

/**
 * For this exercise, youâ€™ll need to read through the source code of the
 * java.util.Scanner class. If input fails when using a Scanner, the Scanner
 * class catches the input exception and closes the resource from which it consumes
 * input. What happens if closing the resource throws an exception? How does this
 * implementation interact with the handling of suppressed exceptions in the try-withresources
 * statement?
 */
public class Task7 {
    public static void main(String[] args) {
    }
}
